### ISSUE TITLE
prophacy -> prophecy?

### ISSUE THREAD

**Issue by happy15** [tyrchen/system_design#1]
https://en.wikipedia.org/wiki/Self-fulfilling_prophecy

**Comment by tyrchen** [comment]
thanks!

**Comment by happy15** [comment]
哈哈，果然写得太急，后面还有些，没有一个个提了。看你的公众号学到很多东西。谢谢你。

Tyr Chen <notifications@github.com>于2018年2月20日周二 下午12:58写道：

**Comment by tyrchen** [comment]
fixed in 0.2.0.
